spring:
  datasource:
    url: jdbc:mysql://localhost:3306/category_product
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update


jwt:
  secret: k205j@dkjf0%^@
  expiration: 330000


server:
  port: 8081